// Dependency-free application tests with simulated DOM/canvas. Not browser visual QA.
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
const source=fs.readFileSync(path.join(root,'dist/app.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
function setup(mode='sprites',calibrated=false){
  const downloads=[],urls=new Map(),draws=[];let counter=0,confirmResult=true;
  class Element{
    get value(){return this._value||''} set value(v){this._value=String(v)}
    constructor(id=''){this.id=id;this.value='';this.type='';this.tagName='DIV';this.listeners={};this.children=[];this.style={};this.classList={toggle(){},add(){},remove(){}};this.clientWidth=1000;this.clientHeight=600;this.disabled=false;}
    addEventListener(name,fn){(this.listeners[name]??=[]).push(fn)}
    async fire(name,extra={}){const event={target:this,preventDefault(){},stopPropagation(){},...extra};if(this['on'+name])await this['on'+name](event);for(const fn of this.listeners[name]||[])await fn(event)}
    appendChild(el){this.children.push(el)}
    replaceChildren(){this.children=[]}
    querySelector(){return new Element()}
    closest(){return new Element()}
    getBoundingClientRect(){return{left:0,top:0,width:parseFloat(this.style.width)||960,height:540}}
    getContext(){return new Proxy({}, {get:(_,key)=>key==='measureText'?text=>({width:text.length*24}):(...args)=>{draws.push({key,args})}})}
    toBlob(fn){setImmediate(()=>fn(new Blob(['test-png'])))}
    setPointerCapture(){} releasePointerCapture(){} focus(){} remove(){}
    click(){if(this.download)downloads.push({name:this.download,blob:urls.get(this.href)});}
  }
  const elements=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element(m[1])]));
  elements.jsonImportMode.value=mode;
  for(const [id,value] of Object.entries({frameValue:'0',poseX:'0',poseY:'0',poseZ:'-600',exportName:'sample_0000'}))elements[id].value=value;
  const doc={activeElement:{tagName:'BODY'},getElementById:id=>{assert.ok(elements[id],'Unknown element '+id);return elements[id]},createElement:()=>new Element(),addEventListener(){},body:new Element()};
  const sandbox={document:doc,window:{addEventListener(){}},Blob,TextEncoder,Uint8Array,Uint32Array,console,crypto:require('node:crypto').webcrypto,confirm:()=>confirmResult,requestAnimationFrame:fn=>fn(),setTimeout:()=>++counter,clearTimeout(){},URL:{createObjectURL:blob=>{const url='blob:'+ ++counter;urls.set(url,blob);return url},revokeObjectURL:url=>urls.delete(url)},Image:class{set src(url){const f=urls.get(url);this.naturalWidth=f.w||100;this.naturalHeight=f.h||100;queueMicrotask(()=>this.onload());}}};
  vm.createContext(sandbox);
  if(calibrated)vm.runInContext(fs.readFileSync(path.join(root,'dist/sprite-box-calibration.js'),'utf8'),sandbox);
  else sandbox.window.SPRITE_BOX_CALIBRATION={id:'legacy-test',assets:[]};
  const expose='globalThis.testAPI={state,loadJson,loadAssets,loadBackground,annotationData,undo,redo,bbox,setZoom,fitCanvas,pushHistory,runExport,removeAsset,addObject,makeZip,filename,resizeBox,boxHandles,setMode,render};';
  vm.runInContext(source.replace(/\}\)\(\);\s*$/,expose+'})();'),sandbox);
  return{api:sandbox.testAPI,e:elements,downloads,draws,setConfirm:v=>confirmResult=v};
}
const sample={frame:0,pose:{x:0,y:0,z:-600},annotations:[{object_id:'jammer',bbox:[1496,1247,1528,1290]},{object_id:'tank',bbox:[888,0,934,13]}],object_counts:{jammer:1,tank:1}};
const file=(data,name='frame_000000.json')=>({name,text:async()=>JSON.stringify(data)});
const png=(name,w=100,h=100)=>({name,type:'image/png',w,h});
let passed=0;
async function test(name,fn){await fn();passed++;console.log('PASS '+name)}
(async()=>{
  await test('JSON fixture round trip',async()=>{const f=process.argv[2],data=f?JSON.parse(fs.readFileSync(f,'utf8')):sample,t=setup();await t.api.loadJson(file(data));assert.deepEqual(clone(t.api.annotationData()),data);});
  await test('pending annotations preserved; missing names visible',async()=>{const t=setup();await t.api.loadJson(file(sample));assert.deepEqual(clone(t.api.annotationData()),sample);assert.match(t.e.importStatus.textContent,/jammer/);assert.equal(t.e.jsonBtn.disabled,false);});
  await test('PNG and ZIP blocked while assets missing',async()=>{const t=setup();await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadJson(file(sample));assert.equal(t.e.zipBtn.disabled,true);await t.api.runExport('zip');assert.equal(t.downloads.length,0);await t.api.runExport('json');assert.equal(t.downloads[0].name,'frame_000000_modified.json');});
  await test('matching PNGs recover exact unequal-aspect boxes',async()=>{const t=setup();await t.api.loadJson(file(sample));await t.api.loadAssets([png('jammer.png',1000,500),png('tank.png',300,200)]);assert.equal(t.api.state.pendingAnnotations.length,0);assert.deepEqual(clone(t.api.annotationData()),sample);});
  await test('undo/redo restores JSON metadata and original source',async()=>{const t=setup();await t.api.loadJson(file(sample));const second={...sample,frame:7,pose:{x:11,y:22,z:33}};await t.api.loadJson(file(second,'other.json'));t.api.undo();assert.deepEqual(clone(t.api.annotationData()),sample);assert.equal(t.e.exportName.value,'frame_000000_modified');t.api.redo();assert.equal(t.api.annotationData().frame,7);});
  await test('undo/redo restores imported assets without dropping instances',async()=>{const t=setup();await t.api.loadJson(file(sample));await t.api.loadAssets([png('jammer.png'),png('tank.png')]);t.api.undo();assert.equal(t.api.state.pendingAnnotations.length,2);assert.equal(t.api.state.assets.length,0);t.api.redo();assert.equal(t.api.state.objects.length,2);assert.deepEqual(clone(t.api.annotationData()),sample);});
  await test('unknown JSON fields survive editing',async()=>{const t=setup(),data=clone(sample);data.extra={version:2};data.pose.pitch=3;data.annotations[0].occlusion=.2;await t.api.loadJson(file(data));await t.api.loadAssets([png('jammer.png')]);assert.deepEqual(clone(t.api.annotationData()),data);});
  await test('invalid import leaves composition untouched',async()=>{const t=setup();await t.api.loadJson(file(sample));await t.api.loadJson(file({...sample,frame:-1}));assert.deepEqual(clone(t.api.annotationData()),sample);await t.api.loadJson(file({...sample,annotations:[{object_id:'',bbox:[1,1,2,2]}]}));assert.deepEqual(clone(t.api.annotationData()),sample);});
  await test('pending-only import replacement asks confirmation',async()=>{const t=setup();await t.api.loadJson(file(sample));t.setConfirm(false);await t.api.loadJson(file({...sample,annotations:[]}));assert.equal(t.api.state.pendingAnnotations.length,2);});
  await test('BOM JSON and special category counts',async()=>{const t=setup(),data={...sample,annotations:[{object_id:'__proto__',bbox:[0,0,1,1]}]};await t.api.loadJson({name:'bom.json',text:async()=>'\uFEFF'+JSON.stringify(data)});assert.equal(t.api.annotationData().object_counts.__proto__,1);});
  await test('zoom caps actual canvas width at both limits',async()=>{const t=setup();for(let i=0;i<50;i++)t.api.setZoom(1.2);const width=t.e.canvasShell.style.width;t.api.setZoom(1.2);assert.equal(t.e.canvasShell.style.width,width);for(let i=0;i<100;i++)t.api.setZoom(1/1.2);const low=t.e.canvasShell.style.width;t.api.setZoom(1/1.2);assert.equal(t.e.canvasShell.style.width,low);});
  await test('background size validation and replacement undo',async()=>{const t=setup();await t.api.loadBackground(png('bad.png',100,100));assert.equal(t.api.state.background,null);await t.api.loadBackground(png('one.png',3840,2160));await t.api.loadBackground(png('two.png',3840,2160));t.api.undo();assert.equal(t.api.state.backgroundName,'one.png');});
  await test('external file drop never adds asset zero',async()=>{const t=setup();await t.api.loadBackground(png('old.png',3840,2160));await t.api.loadAssets([png('object.png')]);await t.e.canvas.fire('drop',{clientX:50,clientY:50,dataTransfer:{getData:()=>'',files:[png('new.png',3840,2160)]}});await new Promise(setImmediate);assert.equal(t.api.state.objects.length,0);assert.equal(t.api.state.backgroundName,'new.png');});
  await test('export snapshot does not change selection and avoids race',async()=>{const t=setup();await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadAssets([png('jammer.png')]);t.api.addObject(0);const uid=t.api.state.selected;const exporting=t.api.runExport('zip');t.e.frameValue.value='99';await exporting;assert.equal(t.api.state.selected,uid);const bytes=Buffer.from(await t.downloads[0].blob.arrayBuffer());assert.ok(bytes.includes(Buffer.from('"frame": 0')));assert.ok(!bytes.includes(Buffer.from('"frame": 99')));});
  await test('UTF-8 ZIP headers and CRC32',async()=>{const t=setup();const bytes=Buffer.from(await t.api.makeZip([{name:'鏍锋湰.json',data:new TextEncoder().encode('123456789')}]).arrayBuffer());assert.equal(bytes.readUInt16LE(6),0x800);assert.equal(bytes.readUInt32LE(14),0xcbf43926);});
  await test('metadata edits can be undone',async()=>{const t=setup();t.e.frameValue.value='3';await t.e.frameValue.fire('change');t.api.undo();assert.equal(t.e.frameValue.value,'0');t.api.redo();assert.equal(t.e.frameValue.value,'3');});
  await test('box mode imports all annotations without PNG in either order',async()=>{for(const bgFirst of [false,true]){const t=setup('boxes');if(bgFirst)await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadJson(file(sample));if(!bgFirst)await t.api.loadBackground(png('bg.png',3840,2160));assert.equal(t.api.state.objects.length,2);assert.equal(t.api.state.assets.length,0);assert.equal(t.api.state.pendingAnnotations.length,0);assert.deepEqual(clone(t.api.annotationData()),sample);assert.equal(t.e.zipBtn.disabled,false);assert.equal(t.e.backgroundModeBtn.disabled,true);}});
  await test('sample 11 boxes restored without PNG',async()=>{const t=setup('boxes'),data=process.argv[2]?JSON.parse(fs.readFileSync(process.argv[2],'utf8')):sample;await t.api.loadJson(file(data));assert.equal(t.api.state.objects.length,data.annotations.length);assert.deepEqual(clone(t.api.annotationData()),data);});
  await test('box dragging updates bbox; undo/redo restores box dimensions',async()=>{const t=setup('boxes'),data={...sample,annotations:[{object_id:'item',bbox:[400,400,800,800]}]};await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadJson(file(data));const evt={button:0,pointerId:1};await t.e.canvas.fire('pointerdown',{...evt,clientX:150,clientY:150});await t.e.canvas.fire('pointermove',{...evt,clientX:175,clientY:160});await t.e.canvas.fire('pointerup',evt);assert.deepEqual(clone(t.api.annotationData().annotations[0].bbox),[500,440,900,840]);t.api.undo();assert.deepEqual(clone(t.api.annotationData().annotations[0].bbox),[400,400,800,800]);t.api.redo();assert.deepEqual(clone(t.api.annotationData().annotations[0].bbox),[500,440,900,840]);});
  await test('all 8 resize handles adjust correct edges, constrain to canvas',async()=>{const t=setup('boxes');await t.api.loadJson(file(sample));const o=t.api.state.objects[0],start=[100,100,500,500];for(const [key,expected] of Object.entries({nw:[50,60,500,500],n:[100,60,500,500],ne:[100,60,101,500],e:[100,100,101,500],se:[100,100,101,101],s:[100,100,500,101],sw:[50,100,500,101],w:[50,100,500,500]})){t.api.resizeBox(o,start,key,50,60);assert.deepEqual(clone(t.api.bbox(o)),expected);}t.api.resizeBox(o,start,'se',9999,9999);assert.deepEqual(clone(t.api.bbox(o)),[100,100,3840,2160]);});
  await test('numeric bounds validate and export new JSON',async()=>{const t=setup('boxes');await t.api.loadJson(file(sample));t.api.state.selected=t.api.state.objects[0].uid;t.api.setMode('object');for(const [i,v] of [10,20,60,90].entries())t.e['box'+i].value=v;await t.e.box0.fire('change');assert.deepEqual(clone(t.api.annotationData().annotations[0].bbox),[10,20,60,90]);t.e.box2.value='5';await t.e.box2.fire('change');assert.deepEqual(clone(t.api.annotationData().annotations[0].bbox),[10,20,60,90]);await t.api.runExport('json');const out=JSON.parse(await t.downloads[0].blob.text());assert.equal(t.downloads[0].name,'frame_000000_modified.json');assert.deepEqual(out.annotations[0].bbox,[10,20,60,90]);});
  await test('later PNG imports do not replace annotation boxes',async()=>{const t=setup('boxes');await t.api.loadJson(file(sample));await t.api.loadAssets([png('jammer.png'),png('tank.png')]);assert.equal(t.api.state.objects.length,2);assert.ok(t.api.state.objects.every(o=>o.annotationOnly));assert.deepEqual(clone(t.api.annotationData()),sample);});
  await test('box copy/delete updates counts and remains independently resizable',async()=>{const t=setup('boxes');await t.api.loadJson(file(sample));t.api.state.selected=t.api.state.objects[0].uid;await t.e.duplicateBtn.fire('click');assert.equal(t.api.annotationData().object_counts.jammer,2);assert.notEqual(t.api.state.objects[0].asset,t.api.state.objects[2].asset);await t.e.deleteBtn.fire('click');assert.equal(t.api.annotationData().object_counts.jammer,1);});
  await test('all labels and boxes render in preview only',async()=>{const t=setup('boxes');await t.api.loadJson(file(sample));t.draws.length=0;t.api.render();assert.equal(t.draws.filter(d=>d.key==='strokeRect').length,2);assert.deepEqual(t.draws.filter(d=>d.key==='fillText').map(d=>d.args[0]),['jammer','tank']);t.draws.length=0;t.api.render(true);assert.equal(t.draws.filter(d=>d.key==='strokeRect'||d.key==='fillText').length,0);});
  const rules=JSON.parse(fs.readFileSync(path.join(root,'dist/sprite-box-calibration.json'),'utf8')).assets;
  const realPNG=(rule,name=rule.filename)=>{const bytes=fs.readFileSync(path.join(root,'../objects',rule.filename));return {name,type:'image/png',w:rule.width,h:rule.height,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}};
  const near=(actual,expected)=>actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<=1.1e-6,`${v} != ${expected[i]}`));
  await test('all 16 real PNGs verified and classified by bytes, even renamed',async()=>{const t=setup('sprites',true);await t.api.loadAssets(rules.map((r,i)=>realPNG(r,i===0?'renamed.png':r.filename)));assert.equal(t.api.state.assets.length,16);for(const a of t.api.state.assets){assert.ok(a.calibration);assert.equal(a.id,a.calibration.class_name)}});
  await test('same-name changed PNG rejected rather than wrongly calibrated',async()=>{const t=setup('sprites',true),f=realPNG(rules[0]);f.arrayBuffer=async()=>new Uint8Array([1,2,3]).buffer;await t.api.loadAssets([f]);assert.equal(t.api.state.assets.length,0);assert.match(t.e.toast.textContent,/不一致/)});
  await test('new unrelated PNG remains explicitly uncalibrated',async()=>{const t=setup('sprites',true),f=realPNG(rules[0],'other.png');f.arrayBuffer=async()=>new Uint8Array([1,2,3]).buffer;await t.api.loadAssets([f]);assert.equal(t.api.state.assets.length,1);assert.equal(t.api.state.assets[0].calibration,null);assert.match(t.e.calibrationStatus.textContent,/0\/1/)});
  await test('all 16 source placements reproduce original official boxes',async()=>{const t=setup('sprites',true);await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadAssets(rules.map(r=>realPNG(r)));for(let i=0;i<rules.length;i++){const r=rules[i],b=r.source_crop_xyxy;t.api.addObject(i,(b[0]+b[2])/2,(b[1]+b[3])/2);near(clone(t.api.bbox(t.api.state.objects.at(-1))),r.source_bbox_xyxy)}});
  await test('rotated nonuniform and reflected reference rectangles use transformed corners',async()=>{const t=setup('sprites',true);await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadAssets(rules.map(r=>realPNG(r)));for(let i=0;i<rules.length;i++){t.api.addObject(i,1200,900);const o=t.api.state.objects.at(-1),b=rules[i].reference_bbox_xyxy;for(const angle of [0,90,37,180,271])for(const sx of [0.6,1.7,-1]){o.rotation=angle*Math.PI/180;o.scale=sx;o.scaleY=.8;const c=Math.cos(o.rotation),s=Math.sin(o.rotation),points=[];for(const x of [b[0],b[2]])for(const y of [b[1],b[3]]){const dx=(x-rules[i].width/2)*sx,dy=(y-rules[i].height/2)*.8;points.push([1200+dx*c-dy*s,900+dx*s+dy*c])}near(clone(t.api.bbox(o)),[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))])}}});
  await test('reference outside image is clipped and fully outside is not exported',async()=>{const t=setup('sprites',true),r=rules.find(r=>r.class_name==='small_launcher');await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadAssets([realPNG(r)]);t.api.addObject(0,0,0);near(clone(t.api.bbox(t.api.state.objects[0])),[0,0,9.5,13.5]);t.api.state.objects[0].x=-1000;assert.equal(t.api.annotationData().annotations.length,0)});
  await test('calibrated bbox JSON import handles asymmetric offsets and instance suffix',async()=>{const t=setup('sprites',true),r=rules.find(r=>r.class_name==='tank');await t.api.loadAssets([realPNG(r)]);const data={frame:0,annotations:[{object_id:'tank_1',bbox:[100,120,200,220]},{object_id:'tank_2',bbox:[400,300,600,550]}]};await t.api.loadJson(file(data));assert.equal(t.api.state.objects.length,2);t.api.annotationData().annotations.forEach((a,i)=>near(clone(a.bbox),data.annotations[i].bbox));assert.notEqual(t.api.state.objects[0].uid,t.api.state.objects[1].uid)});
  await test('calibration survives undo/redo and PNG rendering uses original dimensions',async()=>{const t=setup('sprites',true),r=rules[0];await t.api.loadBackground(png('bg.png',3840,2160));await t.api.loadAssets([realPNG(r)]);t.api.addObject(0);const b=clone(t.api.bbox(t.api.state.objects[0]));t.api.undo();t.api.redo();near(clone(t.api.bbox(t.api.state.objects[0])),b);t.draws.length=0;t.api.render(true);const calls=t.draws.filter(d=>d.key==='drawImage');assert.equal(calls.length,2);assert.deepEqual(calls[1].args.slice(1),[-r.width/2,-r.height/2]);assert.equal(t.draws.filter(d=>d.key==='strokeRect'||d.key==='fillText').length,0)});
  console.log('\n'+passed+' checks passed (simulated DOM/canvas; no visual QA).');
})().catch(e=>{console.error(e);process.exitCode=1});
